name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate composer.json
      run: composer validate
    - name: Install composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run PHPUnit
      run: php7.4 vendor/bin/phpunit
